# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zww0BWZRLcUbz_kBPHhkf_biLmXM6GM7

import cv2

video = cv2.VideoCapture(0)

while True:
	ret, frame = video.read()
	cv2.imshow("Frame", frame)
	k = cv2.waitKey(1)
	if k == ord('q'):
		break

video.release()
cv2.destroyAllWindows()
"""